### ISSUE TITLE
Issue while installing the module with Yarn Berry v4.5.1

### ISSUE THREAD

**Issue by zaosoula** [343dev/optimizt#18] opened 2024-10-19 18:28 UTC
Hello, I'm trying to install version 9.1.0 on OSX, and this error happends

```
# This file contains the result of Yarn building a package (guetzli@https://github.com/343dev/guetzli-bin.git#commit=427cef566261dfcde63c7f8aaebf1a47d8738150)
# Script name: postinstall

Command failed: /Users/zaosoula/Github/--/node_modules/guetzli/vendor/guetzli /Users/zaosoula/Github/--/node_modules/guetzli/test/fixtures/test.jpg /Users/zaosoula/Github/--/node_modules/guetzli/test/fixtures/dest.jpg
Can't open input file


guetzli pre-build test failed
compiling from source
guetzli built successfully
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/Users/zaosoula/Github/--/node_modules/guetzli/vendor/source/guetzli-1.0.1.tar.gz'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/zaosoula/Github/--/node_modules/guetzli/vendor/source/guetzli-1.0.1.tar.gz'
}

Node.js v18.20.2
```

**Comment by zaosoula** [comment] 2024-10-19 18:28
Seems similar to #13

**Comment by 343dev** [comment] 2024-10-20 05:40
Hi @zaosoula, thanks for your bugreport.

Unfortunately, I can't reproduce it on my side. To debug the issue, I will need some additional information.

System:
1. Full version of macOS.
2. Processor architecture (Intel or Apple Silicon).

Environment:
1. How Node.js was installed (installation package from nodejs.org, version manager like nvm, etc.).
2. Current Yarn configuration (result of the command `yarn config list --verbose`).

Clean installation log:
1. Completely clear the Yarn cache with `yarn cache clean` or remove the **guetzli** and **@343dev/optimizt** packages from the cache — `yarn cache clean guetzli && yarn cache clean @343dev/optimizt`.
2. Install the package using the command `yarn add --verbose @343dev/optimizt`.
3. Attach the full installation log here.

I would also be interested to see what happens when you install the package using `npm install --verbose @343dev/optimizt`.

**Comment by 343dev** [comment] 2024-10-21 12:36
Thank you for the provided information.

It seems that the issue is related to how Yarn Berry installs packages from different sources.

When the package is installed from the npm registry:

```json
{
  "dependencies": {
    "guetzli": "^5.0.0"
  }
}
```

or from a locally available file:

```json
{
  "dependencies": {
    "guetzli": "./guetzli-5.0.0.tgz"
  }
}
```

the installed package has the following structure:

```shell
.yarn/unplugged/guetzli-file-8486828326/node_modules/guetzli/
|-- cli.js
|-- index.js
|-- lib
|   |-- index.js
|   `-- install.js
|-- license
|-- package.json
|-- readme.md
|-- test
|   `-- fixtures
|       |-- dest.jpg
|       `-- test.jpg
`-- vendor
    |-- guetzli
    `-- source
        `-- guetzli-1.0.1.tar.gz

6 directories, 11 files
```

However, when the package is installed directly from GitHub, as Optimizt currently does:

```json
{
  "dependencies": {
    "guetzli": "https://github.com/343dev/guetzli-bin/tarball/main"
  }
}
```

the installed package has the following structure:

```shell
.yarn/unplugged/guetzli-https-aba22cc477/node_modules/guetzli/
|-- cli.js
|-- index.js
|-- lib
|   |-- index.js
|   `-- install.js
|-- license
|-- package.json
|-- readme.md
`-- vendor
    `-- guetzli

3 directories, 8 files
```

As you can see, three directories and three files are missing. **During the installation of the “guetzli” package, Yarn Berry seems to remove the “test” and “source” directories.** 🤯

Without these directories, the postinstall script from the package fails.

First, it can’t find files from the “test/fixtures” directory to verify the execution of the guetzli binary:

```
Command failed: /Users/zaosoula/Github/mobilitycare-root/node_modules/guetzli/vendor/guetzli /Users/zaosoula/Github/mobilitycare-root/node_modules/guetzli/test/fixtures/test.jpg /Users/zaosoula/Github/mobilitycare-root/node_modules/guetzli/test/fixtures/dest.jpg
Can't open input file
```

Then, it tries to build the binary from source, but it can’t find the archive with the source code at “vendor/source/guetzli-1.0.1.tar.gz”:

```
Error: ENOENT: no such file or directory, open '/Users/zaosoula/Github/mobilitycare-root/node_modules/guetzli/vendor/source/guetzli-1.0.1.tar.gz'
```

**Comment by 343dev** [comment] 2024-10-22 11:56
@zaosoula, I have just released a new version of Optimizt.

Please install it and let me know if the issue is resolved.

**Comment by 343dev** [comment] 2024-10-27 05:52
I’m closing this as resolved. If you have any further questions, please feel free to reopen it or create a new issue.

**Closed by 343dev** 2024-10-27 05:52 UTC
